<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>


    <script>
        //抛出错误
        function sum(num1, num2) {
            if (!num1 || !num2) {
                throw new Error('参数错误')
            }
        }
        sum(1, 2)


        //捕获错误
        try {
            const p = document.querySelector('p')
            p.innerHTML = 'hello'
        } catch (error) {
            console.log(error);
            console.log(error.message + "未能获取到p标签");
            //可以使用return来终止代码的执行
            // return
            //或者使用throw new Error('错误信息')来抛出错误来终止代码的执行
            throw new Error('错误信息')
        } finally {
            console.log("无论是否有错误都会执行");
        }
        console.log("继续向下执行");
    </script>

</body>

</html>